<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <title>Cetak Kartu Persediaan Tahunan</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&display=swap');
        
        body { 
            font-family: 'Nunito', sans-serif; 
            background: #f8fafc; 
            color: black; 
            margin: 0; 
            padding: 20px; 
            min-height: 100vh;
        }
        
        .report-paper {
            background: white;
            padding: 2rem;
            border-radius: 0.5rem;
            box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);
            width: 100%;
            max-width: 1400px;
            margin: 0 auto;
            overflow-x: auto;
        }
        
        .report-table { border-collapse: collapse; width: 100%; min-width: 800px; margin-bottom: 2rem; }
        .report-table th, .report-table td { border: 1px solid black; padding: 4px; font-size: 11px; }
        .report-table th { text-align: center; font-weight: bold; background-color: #f3f4f6; }
        
        /* Auto repeat header on multiple pages generated by browser */
        .report-table thead { display: table-header-group; }
        .report-table tbody { display: table-row-group; }
        .report-table tr { page-break-inside: avoid; }
        
        .info-table { border-collapse: collapse; margin-bottom: 1rem; font-size: 13px; width: 100%; }
        .info-table td { border: none !important; padding: 2px 4px; }

        @media print {
            body { padding: 0 !important; background: white !important; }
            .no-print { display: none !important; }
            .report-paper {
                padding: 0 !important;
                box-shadow: none !important;
                border-radius: 0 !important;
                max-width: none !important;
                margin: 0 !important;
                overflow: visible !important;
            }
        }
    </style>
</head>
<body>

    <div class="no-print max-w-5xl mx-auto mb-6 p-4 bg-white border border-gray-200 shadow-sm rounded-xl">
        <form method="GET" action="{{ route('reports.kartu.tahunan') }}" class="flex flex-col md:flex-row md:items-end justify-between gap-4">
            <div class="flex flex-col sm:flex-row gap-4 flex-1">
                <div class="w-full sm:w-1/3">
                    <label class="block text-[10px] font-bold text-indigo-700 uppercase mb-1">Dari Tanggal</label>
                    <input type="date" name="start_date" value="{{ $startDate }}" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none">
                </div>
                <div class="w-full sm:w-1/3">
                    <label class="block text-[10px] font-bold text-indigo-700 uppercase mb-1">Sampai Tanggal</label>
                    <input type="date" name="end_date" value="{{ $endDate }}" class="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none">
                </div>
            </div>
            <div class="flex flex-wrap gap-2 text-sm font-bold">
                <a href="{{ route('dashboard') }}" class="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-lg bg-gray-100 border border-gray-300 text-gray-700 hover:bg-gray-200 transition">
                    <i class="fas fa-arrow-left"></i> Kembali ke Dashboard
                </a>
                <button type="submit" class="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition">
                    <i class="fas fa-search"></i> Terapkan Filter
                </button>
                <button type="button" onclick="window.print()" class="inline-flex items-center justify-center gap-2 px-4 py-2 rounded-lg bg-black text-white hover:bg-gray-800 transition">
                    <i class="fas fa-print"></i> Mode Cetak
                </button>
            </div>
        </form>
    </div>

    <div class="report-paper">
        <div class="text-center mb-4 border-b-2 border-black pb-2">
            <h2 class="text-xl font-bold uppercase">KARTU PERSEDIAAN BARANG</h2>
            <div class="text-[12px] font-bold uppercase text-gray-800">DI LINGKUNGAN PEMERINTAH KABUPATEN BOLAANG MONGONDOW SELATAN</div>
            <h5 class="text-xs font-semibold mt-1">Per {{ \Carbon\Carbon::parse($endDate)->translatedFormat('d F Y') }}</h5>
        </div>

        <table class="info-table">
            <tr>
                <td width="140"><strong>SKPD</strong></td>
                <td width="10">:</td>
                <td><strong>{{ $master['opd']['nama'] ?? null ?: $opd->nama_opd ?? '-' }}</strong></td>
            </tr>
            <tr>
                <td><strong>Kabupaten</strong></td>
                <td>:</td>
                <td><strong>Bolaang Mongondow Selatan</strong></td>
            </tr>
        </table>

        @forelse ($grouped as $productKey => $data)
            @php
                $product = $data['product'];
                $rows = $data['rows'] ?? [];
                $saldo = 0;
                $rowNo = 1;
            @endphp
            <table class="report-table">
                <colgroup>
                    <col style="width:4%"> <col style="width:10%"> <col style="width:15%"> <col style="width:12%"> <col style="width:6%"> <col style="width:6%"> <col style="width:6%"> <col style="width:8%"> <col style="width:8%"> <col style="width:8%"> <col style="width:8%"> <col style="width:9%">
                </colgroup>
                <thead>
                    <tr style="border:none !important;">
                        <th colspan="12" style="border:none !important; text-align:left; padding: 2px 0 10px 0 !important; background:none;">
                             <table style="width: 100%; border: none !important; font-size: 13px; line-height: 1.1;">
                                <tr style="border: none !important;">
                                    <td style="border: none !important; width: 140px; padding: 1px !important;"><strong>Nama barang</strong></td>
                                    <td style="border: none !important; width: 10px; padding: 1px !important;">:</td>
                                    <td style="border: none !important; padding: 1px !important;"><strong>{{ $product->name }}</strong></td>
                                </tr>
                                <tr style="border: none !important;">
                                    <td style="border: none !important; padding: 1px !important;"><strong>Satuan</strong></td>
                                    <td style="border: none !important; padding: 1px !important;">:</td>
                                    <td style="border: none !important; padding: 1px !important;">{{ $product->unit }}</td>
                                </tr>
                            </table>
                        </th>
                    </tr>
                    <tr class="bg-gray-100 text-center">
                        <th rowspan="2">No</th><th rowspan="2">Tanggal</th><th rowspan="2">Nomor Surat Dasar Penerimaan / Pengeluaran</th><th rowspan="2">Uraian</th>
                        <th colspan="3">Barang-Barang</th><th rowspan="2">Harga Satuan (Rp)</th><th colspan="3">Jumlah Harga (Rp)</th><th rowspan="2">Keterangan</th>
                    </tr>
                    <tr class="bg-gray-100 text-center uppercase text-[9px]">
                        <th>Masuk</th><th>Keluar</th><th>Sisa</th><th>Masuk</th><th>Keluar</th><th>Sisa</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($rows as $row)
                        @php $saldo += ($row['masuk'] - $row['keluar']); @endphp
                        <tr align="center" style="font-size: 10px;">
                            <td class="text-gray-400">{{ $rowNo++ }}</td>
                            <td>{{ $row['date'] ? \Carbon\Carbon::parse($row['date'])->translatedFormat('d F Y') : '-' }}</td>
                            <td align="left">{{ $row['nosur'] ?? '-' }}</td>
                            <td align="left" class="uppercase font-semibold">{{ $product->name }}</td>
                            <td class="text-green-600 font-bold">{{ $row['masuk'] ?: '-' }}</td>
                            <td class="text-red-500 font-bold">{{ $row['keluar'] ?: '-' }}</td>
                            <td class="font-bold">{{ $saldo }}</td>
                            <td align="right">{{ number_format($row['harga'] ?? 0, 0, ',', '.') }}</td>
                            <td align="right">{{ $row['masuk'] ? number_format($row['masuk'] * ($row['harga'] ?? 0), 0, ',', '.') : '-' }}</td>
                            <td align="right">{{ $row['keluar'] ? number_format($row['keluar'] * ($row['harga'] ?? 0), 0, ',', '.') : '-' }}</td>
                            <td align="right" class="font-bold bg-yellow-50">{{ number_format($saldo * ($row['harga'] ?? 0), 0, ',', '.') }}</td>
                            <td></td>
                        </tr>
                    @endforeach
                    <tr class="bg-gray-50 text-[11px]">
                        <td colspan="6" align="center"><strong>Saldo Per {{ \Carbon\Carbon::parse($endDate)->translatedFormat('d F Y') }}</strong></td>
                        <td align="center"><strong>{{ $saldo == 0 ? 'Nihil' : $saldo }}</strong></td>
                        <td colspan="3"></td>
                        <td align="right"><strong>{{ $saldo == 0 ? 'Nihil' : number_format($saldo * (count($rows)>0 ? ($rows[count($rows)-1]['harga'] ?? 0) : 0), 0, ',', '.') }}</strong></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        @empty
            <div class="py-6 text-center text-gray-400">Tidak ada data</div>
        @endforelse

        @if(!empty($grouped))
        <div class="mt-8 pb-4" style="page-break-inside: avoid;">
            <table class="w-full text-center" style="font-size: 13px; line-height: 1.2;">
                <tr>
                    <td width="50%" align="center">
                        <div style="margin-bottom: 0;">Dibuat Oleh</div>
                        <div style="margin-bottom: 50px;" class="font-semibold">Pengurus Barang</div>
                        <strong><u>{{ $opd->pengurus_nama ?? '' }}</u></strong><br>
                        <div>NIP. {{ $opd->pengurus_nip ?? '' }}</div>
                    </td>
                    <td width="50%" align="center">
                        <div style="margin-bottom: 0;">Mengetahui</div>
                        <div style="margin-bottom: 50px;" class="font-semibold">Kepala Dinas</div>
                        <strong><u>{{ $opd->kepala_nama ?? '' }}</u></strong><br>
                        <div>NIP. {{ $opd->kepala_nip ?? '' }}</div>
                    </td>
                </tr>
            </table>
        </div>
        @endif
    </div>

    <!-- Script auto cetak -->
    <script>
        window.addEventListener('load', function() {
            setTimeout(function() {
                window.print();
            }, 500);
        });
    </script>
</body>
</html>
